Models/ErrorViewModel.cs
using System;

namespace Demo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TransQueue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.Models
{
    public class TransQueue
    {
        public string user_reg_id { get; set; }
        public string trans_queue_type { get; set; }
        public string landoffice_seq { get; set; }
        public string owner_type_id { get; set; }
        public string reg_type_id { get; set; }
        public string juristic_id { get; set; }
        public string juristic_name { get; set; }
        public string evd_type_id { get; set; }
        public string province_seq { get; set; }
        public string amphur_seq { get; set; }
        public string parcel_no { get; set; }
        public string land_no { get; set; }
        public string apppointment_date { get; set; }
        public string survey_date { get; set; }
        public string created_user { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Demo.Models;

namespace Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Controllers
{
    public class MemberController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Reservedlist()
        {
            return View();
        }
        public IActionResult Reservregister1()
        {
            return View();
        }
        public IActionResult Reservregister2()
        {
            return View();
        }
        public IActionResult Reservsurvey1()
        {
            return View();
        }
        public IActionResult Reservsurvey2()
        {
            return View();
        }
        public IActionResult Attachpic()
        {
            return View();
        }
        public IActionResult AttachpicEdit()
        {
            return View();
        }
        public IActionResult Landingpage()
        {
            return View();
        }
        public IActionResult Registercalendar()
        {
            return View();
        }
        public IActionResult Queuecheck()
        {
            return View();
        }
        public IActionResult QueueRconfirm()
        {
            return View();
        }
        public IActionResult Surveycalendar1()
        {
            return View();
        }
        public IActionResult Surveycalendar2()
        {
            return View();
        }
        public IActionResult QueueSconfirm()
        {
            return View();
        }
        public IActionResult AttachSpic()
        {
            return View();
        }
        public IActionResult Userupdate()
        {
            return View();
        }
        public IActionResult Queuepic()
        {
            return View();
        }
        public IActionResult Notification()
        {
            return View();
        }
        public IActionResult QueueCard()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Member/AttachSpic.cshtml
@{
    ViewData["Title"] = "e-Qlands";
}
@section Styles {
    <link href="~/css/member.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <style>
        .attach-header {
            color: white;
        }

        .upload-box-header {
            border-left: solid 4px #6f7a8e;
            background-color: #f3f3f3;
        }

        .gallery-upload {
            color: salmon;
        }

        .image-delete {
            color: red;
        }

        .camera-upload {
            text-align: center;
            background-color: #a7a7a7;
            color: white;
            height: 100px;
            overflow: hidden;
            border-radius: 6px;
        }

            .camera-upload i.fa-camera {
                margin: 20px;
                cursor: pointer;
                font-size: 60px;
            }

        i:hover {
            opacity: 0.6;
        }

        input {
            display: none;
        }
    </style>
}
@{
    int items = 10;
}

<div id="member-bg">
    <div class="row m-3 pt-2">
        <div class="col-12 text-center">
            <div class="d-flex attach-header">
                <div class="p-2" id="back-btn">
                    <i class="fas fa-chevron-left"></i>
                </div>
                <div class="p-2 flex-grow-1" id="attach-header"></div>
            </div>
        </div>
    </div>
    <div class="container pt-3 pb-3" style="background-color:#fff">
        <div class="row m-2">
            <div class="col-12">
                @*Picture1*@
                @for (var i = 1; i <= items; i++)
                {
                    <div class="row p-2 mb-2 upload-box-header">
                        <div class="col-5">
                            <div>รูปที่ @i</div>
                        </div>
                        <div class="col-7">
                            <div class="d-flex justify-content-end">
                                <div class="gallery-upload">
                                    <i class="fa fa-upload p-2" id="gal@(i)">
                                    </i>
                                    <input type="file" id="gallery@(i)" accept="image/*">
                                </div>
                                <div class="image-delete">
                                    <i class="fa fa-trash p-2" id="remove@(i)" style="display:none"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4 camera-upload">
                            <i class="fa fa-camera" id="cam@(i)"></i>
                            <input type="file" id="camera@(i)" accept="image/*" capture />
                            <img id="preview@(i)" src="#" style="width:100%" onerror="this.style.display='none'" />
                        </div>
                        <div class="col-8">
                            <textarea rows="4" class="form-control" placeholder="ใส่ข้อมูลรายละเอียดรูปภาพ" id="info@(i)" disabled></textarea>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>


    <!-- Modal -->
    <!--<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">ประเภทเอกสารหลักฐาน</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <select id="evd_type_id" class="form-control" name="evd_type_id">
                        <option disabled>เลือกประเภทเอกสารหลักฐาน</option>-->
    @*<option selected value="1">โฉนดที่ดิน</option>
        <option value="2">หนังสือรับรองการทำประโยชน์</option>
        <option value="3">หนังสือกรรมสิทธิห้องชุด</option>
        <option value="4">อื่นๆ</option>*@
    <!--</select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ปิดหน้าต่าง</button>
                    <button class="btn btn-primary" id="store-data-btn">ตกลง</button>
                </div>
            </div>
        </div>
    </div>-->
</div>
@section Scripts{
    <script src="~/lib/fileStyle/bootstrap-filestyle.js"></script>
    <script>

    $(function () {

        let attachModel = JSON.parse(localStorage.getItem("typeModel"));
        $('#attach-header').text(attachModel.typeText);

        const transAttach = JSON.parse(localStorage.getItem("transAttach"));
        const attachList = transAttach ? transAttach.filter(t => t.typeId != attachModel.typeId) : [];

        //let attachList = transModel.length > 0 ? transModel : [];
        console.log('model', attachList);


        $('#back-btn').click(function () {
            localStorage.setItem("transAttach", JSON.stringify(attachList));
            let prot = window.location.protocol
            let rootPath = window.location.host;
            //let nextUrl = prot + "//" + rootPath + "/Member/Reservregister2";
            let nextUrl = "@Url.Action("Reservsurver2", "Member")";
            window.location.href = nextUrl;
        });

        function storeItem(index, files, inputEl) {

            let reader = new FileReader();
            reader.onload = function (e) {
                let imageSrc = e.target.result;

                let previewEl = $('#preview' + index);
                let infoEl = $('#info' + index);
                let removeEl = $('#remove' + index);
                let camIcon = $('#cam' + index);

                camIcon.css("display", "none");

                infoEl.prop("disabled", false);

                previewEl.attr('src', imageSrc).css("display", "block");
                removeEl.css("display", "block");

                removeEl.click(function () {
                    // click to remove image
                    let indexItem = attachList.findIndex(x => x.index === index);
                    if (indexItem > -1) {
                        previewEl.css("display", "none");
                        $("i#cam" + index).show();

                        $(this).hide();
                        infoEl.val('');
                        infoEl.prop("disabled", true);
                        attachList.splice(indexItem, 1);
                    }
                    console.log('remove', attachList);
                });

                const attachItemId = attachModel.typeId + "-" + index;
                // store image src
                const item = {
                    image: imageSrc,
                    index: attachItemId,
                    typeId : attachModel.typeId
                };
                attachList.push(item);

                // store info if text is changed
                infoEl.change(function () {
                    let attachItem = attachList.find(x => x.index === attachItemId);
                    attachItem.info = $(this).val();
                    console.log('info', attachList);
                });
            }
            reader.readAsDataURL(files[0]);
        }

        for (i = 1; i < 10; i++) {
            let gal = document.getElementById('gal' + i);
            let galleryInput = document.getElementById('gallery' + i);
            let cam = document.getElementById('cam' + i);
            let cameraInput = document.getElementById('camera' + i);

            gal.addEventListener("click", function () {
                galleryInput.click();
            }, false);
            galleryInput.addEventListener("click", function (evt) {
                evt.stopPropagation();
            }, false);
            cam.addEventListener("click", function () {
                cameraInput.click();
            }, false);
            cameraInput.addEventListener("click", function (evt) {
                evt.stopPropagation();
            }, false);
            cameraInput.addEventListener("change", function () {
                if (this.files && this.files[0]) {
                    let strId = this.id;
                    storeItem(strId.slice(strId.length - 1), this.files, cam);
                }
            }, false);
            galleryInput.addEventListener("change", function () {
                if (this.files && this.files[0]) {
                    let strId = this.id;
                    storeItem(strId.slice(strId.length - 1), this.files, gal);
                }
            }, false);
        }
    });
    </script>
}

Views/Member/Landingpage.cshtml
@{
    ViewData["Title"] = "e-Qlands";
}
@section Styles {
    <link href="~/css/member.css" rel="stylesheet" type="text/css" />
}
<div id="member-bg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 m-5">
               
            </div>
        </div>
    </div>
       
</div>
@section Scripts {
    <script src="https://ws.ega.or.th/cportal/sdk/alpha/sdk.js"></script>
    <script>
        $(function () {
            //$('#submit-login').click(function () {
            //    var settings = {
            //        "url": "https://api.egov.go.th/ws/auth/validate?ConsumerSecret=9Jvx5424jya&AgentID=2459900016656",
            //        "method": "GET",
            //        "timeout": 0,
            //        "headers": {
            //            "Consumer-Key": "4905013d-2fb4-4e0f-802f-8d2dd61956c9"
            //        },
            //    };

            //       $.ajax(settings).done(function (response) {
            //         console.log(response);
            //        });


            //});
            let prot = window.location.protocol
            let rootPath = window.location.host;
            let homePage = prot + "//" + rootPath; 

            window.czpSdk.init().then(() => { window.location = homePage; });  
        });
    </script>
}

Views/Member/Login.cshtml
@{
    ViewData["Title"] = "e-Qlands";
}
@section Styles {
    <link href="~/css/member.css" rel="stylesheet" type="text/css" />
}
<div id="member-bg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 m-5">
                <div class="text-center text-light mb-5">ลงชื่อเข้าใช้งานระบบ</div>
                <div class="text-center text-light mb-5 h1 ">e-QLands</div>
                <div class="form-group">
                    <label class="text-light" for="username">Username</label>
                    <input maxlength="13" type="number" name="user_name"  class="form-control" id="username" placeholder="เลขบัตรประชาชน(13หลัก)" required>

                </div>
                <div class="form-group ">
                    <label class="text-light" for="password">Password</label>
                    <input type="number" name="user_pwd" maxlength="10"  class="form-control" id="password" placeholder="หมายเลขโทรศัพท์" required>
                </div>
                <div class="form-check mb-2">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Remember Me</label>
                </div>
                <div class="row">
                    <div class="col-6">
                        <a asp-controller="Member" asp-action="Register" class="btn btn-block btn-secondary"><i class="fas fa-user"></i>&nbspลงทะเบียน</a>
                    </div>
                    <div class="col-6">
                        <button class="btn btn-block btn-primary" style="background-color: #ff6a00" id="submit-login">เข้าสู่ระบบ&nbsp<i class="fas fa-sign-in-alt"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Back Modal*@
    <div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row justify-content-center mb-4">
                        <i class="fas fa-exclamation-triangle fa-7x" style=" color:#f0dc51;"></i>
                    </div>

                    <div class="row justify-content-center ">
                        <p>หมายเลขบัตรประชาชน(13 หลัก)</p>                        
                    </div>

                    <div class="row justify-content-center ">
                         <p>หรือ หมายเลขโทรศัพท์ ไม่ถูกต้อง </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ตกลง</button>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(function () {
            $('#submit-login').click(function () {
                //let userName = $("input[name='user_name']").val();
                let userName = $("#username").val();
                let uPass = $("input[name='user_pwd']").val();
               
                console.log(userName);
                console.log(uPass);
                const data = {
                    user_name: userName,
                    user_pwd: uPass,
                    device_token: userName 
                };
                console.log('data', data);
                let url = 'https://eqlands.dol.go.th/eQLands/api/Service/Login';
                $.ajax({
                    url: url,
                    dataType: "json",
                    type: "POST",
                    data: data
                  
                }).done(function (data) {
                    let res = data.records[0];
                    console.log('userinfo:', res);
                    if (!res) {
                        //do somthing
                        $('#alertModal').modal('show');
                    } else {
                        localStorage.setItem("userinfo", JSON.stringify(res));
                        //let prot = window.location.protocol
                        //let rootPath = window.location.host;
                        let nextUrl = "@Url.Action("Reservedlist", "Member")";
                        window.location.href = nextUrl;
                    }
                    
                });

              });
        });
    </script>
}

Views/Member/Notification.cshtml
@{
    ViewData["Title"] = "e-Qlands";
}
@section Styles {
    <link href="~/css/member.css" rel="stylesheet" type="text/css" />
    <style>
        .trim-border {
            border-radius: 6px;
        }

        .wrap {
            word-wrap: break-word;
        }
        .queue-check {
            position: absolute;
            border-radius: 50%;
            background-color: aqua;
            padding: 5px 10px;
            font-size: 1.2rem;
            right: 40px;
            border-color: transparent;
        }

        .noti-delete {
            position: absolute;
            padding: 5px 10px;
            font-size: 1.5rem;
            right: 20px;
            background-color: transparent;
            border-color: transparent;
            color: red;
          
        }

        .header-nav {
            z-index: 100;
            width: 100%;
            position: fixed;
            top: 0;
            height: 60px;
            background-color: #546A6C;
        }

        .flex-block {
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: #fff;
            height: 60px;
            margin: 0 14px;
        }

            .flex-block button {
                color: #fff;
                
            }

            .flex-block .flex-l-item div {
                display: inline-block;
            }

            .flex-block .flex-r-item {
              
            }
    </style>
}
<div id="member-bg">
    
    <div class="header-nav">
        <div class="flex-block">
            <div class="flex-l-item">
                <div>
                    <button id="back-btn" class="btn"><i class="fas fa-chevron-left"></i></button>
                </div>
                <div>การแจ้งเตือน</div>
            </div>
            <div class="flex-r-item">
                <div>

                    <button class="btn" id="clearall"><u>ลบทั้งหมด</u></button>
                </div>
                @*<button class="btn"><i class="far fa-bell"></i></button>*@
            </div>
        </div>

    </div>
    <div class="container" style="margin-top: 60px">
        <div class="row justify-content-center">
            <div class="col-12" id="Notification">
            </div>

        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class=" text-center " id="exampleModalLabel">รายการยื่นคำขอจองคิว</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <a asp-controller="Member" asp-action="Reservregister1" class="btn btn-block btn-success">จองคิวจดทะเบียน</a>
                    <a asp-controller="Member" asp-action="Reservsurvey1" class="btn btn-block btn-success">จองคิวรังวัด</a>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-block" data-dismiss="modal">ปิดหน้าต่าง</button>

                </div>
            </div>
        </div>
    </div>

    @*cancel Modal*@
    <div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row justify-content-center mb-4 ">
                        <i class="far fa-question-circle fa-7x" style="  color: #26d1d1;"></i>
                    </div>

                    <div class="row justify-content-center ">
                        <p>คุณต้องการยกเลิกจองคิวใช่หรือไม่</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ไม่</button>
                    <button class="btn btn-primary text-light" type="button" id="cancleQueue">ใช่</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script>

        $(function () {
             let userdata = JSON.parse(localStorage.getItem("userinfo"));
            console.log('userdata', userdata)
            const data = {
                user_reg_id: userdata.user_reg_id
            };

            let url = 'https://eqlands.dol.go.th/eQLands/api/Service/GetNotification';
            $.ajax({
                url: url,
                dataType: "json",
                type: "GET",
                data: data
            }).done(function (data) {
                console.log('Data', data);
                if (data.total !== 0) {
                    for (var i = 0; i < data.total; i++) {
                        let notiid = data.records[i].trans_queue_approve_id;
                        let uid = data.records[i].user_reg_id;
                        console.log('type', data.records[i].reg_type_name);
                        if (data.records[i].notify_flag == "1") {
                            $('#Notification').append(
                                `<button class="noti-delete" id="notidelete${notiid}" ><i class="fas fa-trash-alt"></i></button>
                                <div class="bg-light p-2 trim-border mb-3 noti-card" >
                                    <div class ="form-inline trim-border p-1" style="background-color:gray">
                                           <input type="hidden" id="noti-card-id" value="${notiid}"/>
                                         <div><img src="../img/2.png" class="rounded float-left" width="30"></div>
                                         <div >&nbspข้อความวันที่&nbsp${data.records[i].notify_date}</div>
                                    </div><hr>
                                    <div>จาก : ${data.records[i].org_name}</div >
                                    <div class ="form-inline justify-content-between">
                                         <div>เลขคิว : ${data.records[i].trans_queue_code}&nbsp</div >
                                         <div>วันที่ทำการตรวจ : ${data.records[i].approve_date}</div >
                                    </div>
                                    <div>ประเภทคำขอ : ${data.records[i].reg_type_name}</div >
                                    <div class="wrap">สถานะ : ${data.records[i].approve_detail}</div >
                                </div>`
                            );
                        }
                        else {
                            $('#Notification').append(
                                `<button class="noti-delete" id="notidelete${notiid}"> <i class="fas fa-trash-alt"></i></button>
                                <div class="bg-light p-2 trim-border mb-3 noti-card" >
                                    <div class ="form-inline trim-border p-1" style="background-color:lightgray">
                                           <input type="hidden" id="noti-card-id" value="${notiid}"/>
                                         <div><img src="../img/2.png" class="rounded float-left" width="30"></div>
                                         <div >&nbspข้อความวันที่&nbsp${data.records[i].notify_date}</div >
                                    </div><hr>
                                    <div>จาก : ${data.records[i].org_name}</div >
                                    <div class ="form-inline justify-content-between">
                                         <div>เลขคิว : ${data.records[i].trans_queue_code}&nbsp</div >
                                         <div>วันที่ทำการตรวจ : ${data.records[i].approve_date}</div >
                                    </div>
                                    <div>ประเภทคำขอ : ${data.records[i].reg_type_name}</div >
                                    <div class="wrap">สถานะ : ${data.records[i].approve_detail}</div>
                                </div>`
                            );
                        }

                        $(`#notidelete${notiid}`).click(function () {
                         
                            let tqaid = JSON.stringify(notiid);
                            let uregid = JSON.stringify(uid);
                            let deletenoti = {
                                trans_queue_approve_id: tqaid,
                                user_reg_id: uregid
                            };

                            let delurl = 'https://eqlands.dol.go.th/eQLands/api/Service/DeleteNotification?' + 'trans_queue_approve_id=' + tqaid + '&' + 'user_reg_id=' + uregid;
                            $.ajax({
                                url: delurl,
                                dataType: "json",
                                type: "POST",
                                //data: deletenoti
                            }).done(function (data) {
                                let nextUrl = "@Url.Action("Notification", "Member")";
                                window.location.href = nextUrl;
                            });
                        });


                        $(".noti-card").on('click', function (event) {
                            event.stopPropagation();
                            event.stopImmediatePropagation();
                            const noTiId = $(this).find('#noti-card-id').val();                            
                            let uregid = JSON.stringify(uid);
                            let readnoti = {
                                trans_queue_approve_id: noTiId,
                                user_reg_id: uregid
                            };

                            let readurl = 'https://eqlands.dol.go.th/eQLands/api/Service/SetReadNotification?' + 'trans_queue_approve_id=' + noTiId + '&' + 'user_reg_id=' + uregid;
                            $.ajax({
                                url: readurl,
                                dataType: "json",
                                type: "POST",
                                //data: readnoti
                            }).done(function (data) {
                                let nextUrl = "@Url.Action("Notification", "Member")";
                                window.location.href = nextUrl;
                            });
                        });


                    }
                }
                else {
                   
                    $('#Notification').append(
                        //`<div class="bg-light p-2 trim-border mb-3 mt-3 text-center">ไม่มีข้อความแจ้งเตือน</div>`
                            `<div class="text-center text-light mt-4">ไม่มีข้อความแจ้งเตือน</div>`
                    );
                }
            });

            $('#back-btn').click(function () {
                 let nextUrl = "@Url.Action("Reservedlist", "Member")";
                 window.location.href = nextUrl;
            });
            $('#clearall').click(function () {

                let readurl = 'https://eqlands.dol.go.th/eQLands/api/Service/DeleteAllNotification?' + 'user_reg_id=' + userdata.user_reg_id;
                            $.ajax({
                                url: readurl,
                                dataType: "json",
                                type: "POST",
                                //data: readnoti
                            }).done(function (data) {
                                let nextUrl = "@Url.Action("Notification", "Member")";
                                window.location.href = nextUrl;
                            });
               });
        });

    </script>

}